### ISSUE TITLE
2022 in helium-tax tool dropdown

### ISSUE THREAD

**Issue by redx1134** [davetapley/helium-tax#56]
my first day using github, tried searching for this but pulled up no results.  In the helium-tax tool, 2022 isn't avilable in the dropdown.  Is that something I can add somehow?  Or something that will be added before month's end?  Asking because I do monthly payouts to my hosts and if it's not going to be, I'll need to figure out a different way to pull their earnings for the month before it gets here.  Thanks in advance.

**Comment by davetapley** [comment]
Thanks for reminding me!
Should be live shortly!

**Comment by redx1134** [comment]
my hero, donating more helium for the assist!

**Comment by redx1134** [comment]
is something happening to the 2022 tab on the tax tool?

**Comment by DTB-K** [comment]
> is something happening to the 2022 tab on the tax tool?

I just came to do my monthly figures and noticed the same.  2022 is no longer an option.

**Comment by redx1134** [comment]
lol, exactly what I did.  I do pay outs on the first.  Had to do them the old fashioned way by hand.  I know the network has been doing some stuff lately, wondered if that had impacted the tax tool in some way.
