### ISSUE TITLE
Support Validator Rewards

### ISSUE THREAD

**Issue by tyler-whitman** [davetapley/helium-tax#64]
The tool works great for hotspots in an account but doesn't pick up validators or allow input for a specific validator address.

EG: https://explorer.helium.com/validators/11TUnQ3vcDm2328rgqRUdhyGR4MdWyTFJYPtGy1pnm63ANwpPRC

**Comment by davetapley** [comment]
@tyler-whitman well it merged and deployed, but I'm getting "⚠️ No rewards" with `11TUnQ3vcDm2328rgqRUdhyGR4MdWyTFJYPtGy1pnm63ANwpPRC`, do you see the same?

**Comment by tyler-whitman** [comment]
Weird it is because of `GET https://api.helium.io/v1/validators/11TUnQ3vcDm2328rgqRUdhyGR4MdWyTFJYPtGy1pnm63ANwpPRC net::ERR_FAILED 503` the fetch on validator address is failing. We might be getting rate limited on the helium API, because the call works for me when I fetch it independently

**Comment by tyler-whitman** [comment]
It seems to be working for me now, make sure you set it to 2022 that validator has no rewards before that.

**Comment by kujenga** [comment]
I was seeing an issue where the version of the helium-js client library used by this repo was out of date, on an older version that did not support validators. I submitted a PR here that fixes that issue as well as some other small improvements for validators: https://github.com/davetapley/helium-tax/pull/76
