### ISSUE TITLE
Cache Oracle prices

### ISSUE THREAD

**Issue by davetapley** [davetapley/helium-tax#83]
Instead of #5 and to mitigate #79 I'll just pull all the block prices and stick them in a JSON.

Since this requires having all prices, I'll limit to 2020 and 2021 for now, and then implement proper fix on #79 (probably after tax filing).

---

Could also get from https://github.com/dewi-alliance/dewi-etl/blob/main/db_schema.dbml#L158-L161 maybe via https://github.com/dewi-alliance/dewi-etl/issues/3 ?

**Comment by cheezedawg** [comment]
Doesn't seem to be working for me- not sure if its related to this rate limiting. When I enter my hotspot address, it spins for a while and then says no rewards during 2021 (there were). So then I enter the wallet address, and it spins for a while and then... nothing. No CSV, or any visible results. 

I appreciate your work with this tool.

**Comment by davetapley** [comment]
@cheezedawg hmm, I just tried a few again and it seems to be working now (albeit _extremely_ slowly), all I can do is recommend trying again (perhaps at different times of the day) 😞

**Comment by cheezedawg** [comment]
Thanks Dave. I’ve been trying periodically and will keep trying. How slow?
Minutes? Hours?

Do you recommend using the hotspot address or wallet address? I only have 1
hotspot in the wallet, but the behavior is different as noted above.

Sorry I missed this before posting a new discussion.

**Comment by sisqonrw** [comment]
hi can me give someone step by step commands for user that are not expert. i am thinking prefer it and find it nice if someone can help non experts.

which file do we need?
how can we edit it?
which commands should we add and delete?

thanks

**Comment by cheezedawg** [comment]
I'm not sure what you are asking. You just need to input your hotspot or wallet address into the tool. It will then download a CSV file that you can open in Excel or other spreadsheet software to calculate your mining income.

**Comment by sisqonrw** [comment]
ok where can i download the tool?

**Comment by sisqonrw** [comment]
how can i edit the tool or file?
