### ISSUE TITLE
Enhancement Suggestion - Monthly instead of Yearly

### ISSUE THREAD

**Issue by michael2112** [davetapley/helium-tax#84]
How about switching your solution to download by the month? Add a month dropdown. My situation is such that my taxes are done on a fiscal year end (3/31 in my case), not a calendar year. Plus, if the earnings throughout the year effect a person's (or business's) income enough, they could also need the information to file quarterly estimated tax payments.

I am not enough of a programmer to be able to tell if making the output download smaller would help performance on your system or against whatever API you may be using, but maybe that would be a benefit too.  Thank you...!

**Comment by davetapley** [comment]
I would consider if enough interest, please discuss here: https://github.com/davetapley/helium-tax/discussions/80
